FROM python:3.11-slim

WORKDIR /app

COPY requirements_mqtt_simulator.txt .
RUN pip install --no-cache-dir -r requirements_mqtt_simulator.txt

COPY mqtt_device_simulator.py .

CMD ["python", "mqtt_device_simulator.py"]

